# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JAVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdk_version', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'java',
            },
        ),
        migrations.CreateModel(
            name='PHP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('php_version', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'php',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='depoloyment',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='node',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='node',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='node',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='node',
            name='node_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterModelTable(
            name='node',
            table='node',
        ),
        migrations.AddField(
            model_name='application',
            name='setting',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.Setting'),
            preserve_default=False,
        ),
    ]
