# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20170526_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='setting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Setting'),
        ),
    ]
