# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', through='project.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
